In [1]:
import numpy as np

## listi numpy arrayine (matrise) donusturur

In [34]:
list=[20,30,40]
np.array(list)

array([20, 30, 40])

In [6]:
matrixList= [[10,20,30],[50,40,30],[10,20,60]]

In [8]:
np.array(matrixList)

array([[10, 20, 30],
       [50, 40, 30],
       [10, 20, 60]])

In [9]:
np.arange(0,15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [12]:
np.arange(0,15,2) #step=2

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [16]:
np.zeros((2,2))
#np.zeros((dim))
#(dim)

array([[0., 0.],
       [0., 0.]])

In [17]:
np.ones((3,1))

array([[1.],
       [1.],
       [1.]])

In [20]:
#linspace
np.linspace(5,7)
#5'ten 7'ye esit araliklarli array olusturur

array([5.        , 5.04081633, 5.08163265, 5.12244898, 5.16326531,
       5.20408163, 5.24489796, 5.28571429, 5.32653061, 5.36734694,
       5.40816327, 5.44897959, 5.48979592, 5.53061224, 5.57142857,
       5.6122449 , 5.65306122, 5.69387755, 5.73469388, 5.7755102 ,
       5.81632653, 5.85714286, 5.89795918, 5.93877551, 5.97959184,
       6.02040816, 6.06122449, 6.10204082, 6.14285714, 6.18367347,
       6.2244898 , 6.26530612, 6.30612245, 6.34693878, 6.3877551 ,
       6.42857143, 6.46938776, 6.51020408, 6.55102041, 6.59183673,
       6.63265306, 6.67346939, 6.71428571, 6.75510204, 6.79591837,
       6.83673469, 6.87755102, 6.91836735, 6.95918367, 7.        ])

In [30]:
np.eye(5)
#identity matrix
#when i=j, array[i][j]=1

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# 0'dan 10'a kadar esit aralikli 20 tane sayi

In [33]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

## random

In [37]:
np.random.rand(3,4)
#3x4'luk array olusturma
#row,column

array([[0.05842562, 0.08380412, 0.91818446, 0.32269813],
       [0.21965482, 0.22586376, 0.24083935, 0.32270803],
       [0.69495476, 0.84221855, 0.62378648, 0.34653394]])

In [50]:
np.random.randint(0,10)
#returns integer
#0 dahil, 10 dahil degil

0

In [52]:
np.random.randint(0,20,5)
#0'dan 20'ye 5 elemanli integer array dondurur

array([17, 16,  9, 18,  5])

In [53]:
array=np.arange(30)

In [55]:
print(array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


In [56]:
array=np.random.rand(2,5)
print(array)

[[0.18206792 0.11544724 0.44316474 0.85121949 0.59946184]
 [0.59722497 0.9453377  0.01203699 0.01854057 0.41460999]]


In [61]:
array2=np.random.randint(-5,10,(2,4))
print(array2)
#2x4'luk matris

[[-5  7  2  6]
 [-4  6  4  0]]


In [81]:
arrWith20elements=np.random.randint(1,11,20)

In [82]:
print(arrWith20elements)

[ 9  7  5  4  6 10  6 10  7  7  5  2  2  2  7  5 10  2  6  8]


In [84]:
arrWith20elements.reshape(4,5)
#20 elemani 4x5'lik matrise donusturdu
#row x column sayisi, bolunecek dizinin eleman sayisine esit olmalidir

array([[ 9,  7,  5,  4,  6],
       [10,  6, 10,  7,  7],
       [ 5,  2,  2,  2,  7],
       [ 5, 10,  2,  6,  8]])

In [85]:
arrWith20elements.max()

10

In [86]:
arrWith20elements.min()

2

In [87]:
arrWith20elements.argmax() 
#max elemanin kacinci indexte oldugunu verir

5

In [89]:
arrWith20elements.argmin() 
#min elemanin kacinci indexte oldugunu verir

11

In [92]:
arrWith20elements.shape

(20,)

In [94]:
arrWith20elements
#reshape yapmamiza ragmen ilk bastaki hali degismedi

array([ 9,  7,  5,  4,  6, 10,  6, 10,  7,  7,  5,  2,  2,  2,  7,  5, 10,
        2,  6,  8])

In [95]:
reshapedArray= arrWith20elements.reshape(4,5)

In [96]:
reshapedArray

array([[ 9,  7,  5,  4,  6],
       [10,  6, 10,  7,  7],
       [ 5,  2,  2,  2,  7],
       [ 5, 10,  2,  6,  8]])

In [97]:
reshapedArray.shape

(4, 5)