In [1]:
import numpy as np

In [3]:
arr=np.arange(20)

In [6]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [7]:
arr[5]

5

In [12]:
arr[3:10]
#3-10. indexler arasindaki elemanlari getirir.
#stopping index yani 10 dahil degildir

array([3, 4, 5, 6, 7, 8, 9])

In [15]:
arr[3:10]=-2
#start ve end indexler arasi tum elemanlari "-2" yapti

In [16]:
arr

array([ 0,  1,  2, -2, -2, -2, -2, -2, -2, -2, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [18]:
newArr=np.arange(0,16)

In [19]:
newArr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [20]:
slicingArr=newArr[4:9]

In [22]:
slicingArr

array([4, 5, 6, 7, 8])

In [29]:
slicingArr[:]=5
#changed all elements in array to "5"

In [30]:
slicingArr

array([5, 5, 5, 5, 5])

In [33]:
newArr

array([ 0,  1,  2,  3,  5,  5,  5,  5,  5,  9, 10, 11, 12, 13, 14, 15])

In [34]:
#slicing dizisinde degistirmistik, slicing dizisini turettigimiz arrayin
#ilgili elemanlari da degistirilmis oldu

In [54]:
anotherArr = np.arange(0,24)
anotherArr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [59]:
tempArr= anotherArr.copy()
tempArr
#degismemesi icin tempArray olusturdum

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [60]:
anotherArr3= tempArr[3:15]
anotherArr3
#slicing ile olusturulan array

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [57]:
anotherArr3[1:5]=-6
anotherArr3

array([ 3, -6, -6, -6, -6,  8,  9, 10, 11, 12, 13, 14])

In [61]:
anotherArr
#degismemis oldu

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])