In [2]:
import numpy as np

In [3]:
myList=[[10,40,50],[20,30,70],[10,30,90]]

In [4]:
myList

[[10, 40, 50], [20, 30, 70], [10, 30, 90]]

In [5]:
myMatrix=np.array(myList)
myMatrix

array([[10, 40, 50],
       [20, 30, 70],
       [10, 30, 90]])

In [6]:
myMatrix.shape

(3, 3)

In [7]:
myMatrix[0]

array([10, 40, 50])

In [8]:
myMatrix[0][1]

40

In [9]:
myMatrix[0,1]

40

In [10]:
#myMatrix[0][1] ve myMatrix[0,1] yazmak ayni islemler

In [11]:
myMatrix[1:,2]
#index=1 satirdan baslayip son satira kadar, 0-2 arasi index degerine sahip
#sutunlari getirir

array([70, 90])

In [12]:
anotherMatrix=np.array([[10,40,50,25],[20,15,30,70],[10,45,30,90],
                        [15,25,35,50],[20,70,85,90]])
anotherMatrix

array([[10, 40, 50, 25],
       [20, 15, 30, 70],
       [10, 45, 30, 90],
       [15, 25, 35, 50],
       [20, 70, 85, 90]])

In [13]:
anotherMatrix[1:,3]

array([70, 90, 50, 90])

In [14]:
anotherMatrix[0:,2:]

array([[50, 25],
       [30, 70],
       [30, 90],
       [35, 50],
       [85, 90]])

In [15]:
anotherMatrix[0:,3:]

array([[25],
       [70],
       [90],
       [50],
       [90]])

In [16]:
newList=[[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14],
         [15,16,17,18,19],[20,21,22,23,24]]

In [17]:
newMatrix=np.array(newList)
newMatrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [18]:
newMatrix[[0,2,4]] #0,2 ve 4. indexleri getirdi

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

In [19]:
newMatrix[[1,3,0]]

array([[ 5,  6,  7,  8,  9],
       [15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4]])