In [1]:
import numpy as np

In [8]:
arr=np.random.randint(1,100,20)

In [9]:
arr

array([38, 27, 95, 79, 91,  4, 21,  2, 54, 14,  4, 88, 39, 51, 54, 27, 89,
       43, 90, 13])

In [10]:
arr>24

array([ True,  True,  True,  True,  True, False, False, False,  True,
       False, False,  True,  True,  True,  True,  True,  True,  True,
        True, False])

In [14]:
boolArr= arr>24
#baska bir dizinin icine atabiliriz

In [15]:
boolArr

array([ True,  True,  True,  True,  True, False, False, False,  True,
       False, False,  True,  True,  True,  True,  True,  True,  True,
        True, False])

In [17]:
arr[boolArr]
#true olanlari dondurur

array([38, 27, 95, 79, 91, 54, 88, 39, 51, 54, 27, 89, 43, 90])

In [32]:
arr2=np.arange(0,24)

In [33]:
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [34]:
arr2+arr2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46])

In [35]:
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [36]:
arr2*arr2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529])

In [37]:
arr2-arr2

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [40]:
arr2/arr2
#hata degil uyari verir, 0/0 yuzunden

C:\Users\ecems\AppData\Local\Temp/ipykernel_15608/3211272386.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr2/arr2


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [41]:
np.sqrt(arr2)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152])

In [42]:
np.max(arr2)

23

In [43]:
np.min(arr2)

0